export {default as Home} from './Home'
export {default as One} from './One'
export {default as Two} from './Two'
export {default as Contact} from './Contact'
export {default as Sidebar} from './Sidebar'
export {default as Footer} from './Footer'
